### ISSUE TITLE
锁链装备替换不正常

### ISSUE THREAD

**Issue by ReallyErYZ** [Caritusy/RE-JavaTexturePackage2NeteaseBedrockTexturePackage#4]
如题

**Comment by Caritusy** [comment]
请问您正在使用什么材质包呢？如果可以，请提供下载链接。
网易的游戏版本是多少呢？
请提供以上信息，以方便开发者更好的修复您提到的“锁链装备替换不正常”的问题。

**Comment by ReallyErYZ** [comment]
> 请问您正在使用什么材质包呢？如果可以，请提供下载链接。 网易的游戏版本是多少呢？ 请提供以上信息，以方便开发者更好的修复您提到的“锁链装备替换不正常”的问题。

游戏版本为Elysium适配的版本，材质包下载链接为[§5Violet §bDreams §dV2.zip](https://wwhf.lanzout.com/ibaNQ1cb23yj)密码1337

**Comment by Caritusy** [comment]
![image](https://github.com/user-attachments/assets/ef9a6d59-7527-453c-a3ea-60092c911ce4)
很遗憾，没看出来什么问题...
请您使用最新版本并进行重试...
如果您在下载<a href="https://github.com/Caritusy/RE-JavaTexturePackage2NeteaseBedrockTexturePackage/releases/tag/V240825"> 最新版本 </a>后依然有该问题，请附上相关截图！
